package es.ugr.ddsi.interfaz;

import es.ugr.ddsi.MainFestival;
import es.ugr.ddsi.model.Grupo;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class MenuGrupos extends javax.swing.JFrame {

    private final MainFestival festival;
    
    private ArrayList<Grupo> grupos;
    /**
     * Creates new form MenuGrupos
     * @param festival
     */
    public MenuGrupos(MainFestival festival) {
        this.festival = festival;
        initComponents();
        
        try {
            PreparedStatement stm = festival.getConnection().prepareStatement("SELECT * FROM GRUPO");
            ResultSet rs = stm.executeQuery();
            
            grupos = new ArrayList<>();
            while (rs.next()) {
                grupos.add(new Grupo(
                        rs.getString("id_grupo"),
                        rs.getString("nombre_grupo"),
                        rs.getString("email_grupo"),
                        rs.getString("telefono_grupo"),
                        rs.getInt("cache_grupo")
                ));
            }
            
            listaGrupos = new javax.swing.JList(grupos.toArray());
            scrollGrupos.setViewportView(listaGrupos);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollGrupos = new javax.swing.JScrollPane();
        listaGrupos = new javax.swing.JList<>();
        labelEdicionActual = new javax.swing.JLabel();
        botonOfertar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        botonAsignarManager = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaGrupos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Grupo 1", "Grupo 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaGrupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaGrupos.setToolTipText("");
        scrollGrupos.setViewportView(listaGrupos);

        labelEdicionActual.setText("Grupos en la edición actual");

        botonOfertar.setText("Ofertar");
        botonOfertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOfertarActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(255, 51, 51));
        botonVolver.setText("Volver");
        botonVolver.setToolTipText("Volver al menú anterior");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonAsignarManager.setText("Asignar Manager");
        botonAsignarManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollGrupos)
                    .addComponent(botonOfertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEdicionActual)
                        .addGap(0, 561, Short.MAX_VALUE))
                    .addComponent(botonAsignarManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelEdicionActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonOfertar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAsignarManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOfertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOfertarActionPerformed
        int chosenIndex = listaGrupos.getSelectedIndex();
        if (chosenIndex == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un grupo al que ofertar", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Grupo ofertado = grupos.get(chosenIndex);
        if (ofertado == null) {
            JOptionPane.showMessageDialog(this, "No se ha podido determinar el grupo seleccionado", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new MenuOfertarGrupo(festival, ofertado).setVisible(true);
        });
    }//GEN-LAST:event_botonOfertarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            this.setVisible(false);
        });
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonAsignarManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarManagerActionPerformed
        int chosenIndex = listaGrupos.getSelectedIndex();
        if (chosenIndex == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un grupo al que asignar un manager", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Grupo ofertado = grupos.get(chosenIndex);
        if (ofertado == null) {
            JOptionPane.showMessageDialog(this, "No se ha podido determinar el grupo seleccionado", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_botonAsignarManagerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignarManager;
    private javax.swing.JButton botonOfertar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel labelEdicionActual;
    private javax.swing.JList<String> listaGrupos;
    private javax.swing.JScrollPane scrollGrupos;
    // End of variables declaration//GEN-END:variables
}
