
package es.ugr.ddsi.interfaz;

import es.ugr.ddsi.MainFestival;
import es.ugr.ddsi.model.Grupo;
import es.ugr.ddsi.model.Manager;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class MenuAsignarManager extends javax.swing.JFrame {

    private final MainFestival festival;
    private final Grupo grupo;
    private ArrayList<Manager> managers;

    public MenuAsignarManager(MainFestival festival, Grupo grupo) {
        this.festival = festival;
        this.grupo = grupo;
        initComponents();
        
        try {
            PreparedStatement stm = festival.getConnection().prepareStatement("SELECT * FROM MANAGER");
            ResultSet rs = stm.executeQuery();
            
            managers = new ArrayList<>();
            while (rs.next()) {
                managers.add(new Manager(
                        rs.getString("id_manager"),
                        rs.getString("nombre"),
                        rs.getString("email"),
                        rs.getString("telefono")
                ));
            }
            
            jListManagers = new javax.swing.JList(managers.toArray());
            scrollManagers.setViewportView(jListManagers);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        labelGrupo = new javax.swing.JLabel();
        scrollManagers = new javax.swing.JScrollPane();
        jListManagers = new javax.swing.JList<>();
        botonVolver = new javax.swing.JButton();
        botonAsignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Selecciona el mánager que llevará esta edición a:");

        labelGrupo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        labelGrupo.setText(grupo.getNombre());

        jListManagers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollManagers.setViewportView(jListManagers);

        botonVolver.setBackground(new java.awt.Color(255, 51, 51));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonAsignar.setBackground(new java.awt.Color(0, 204, 204));
        botonAsignar.setText("Asignar mánager");
        botonAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrollManagers)
                            .addComponent(botonAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollManagers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarActionPerformed
        int chosenIndex = jListManagers.getSelectedIndex();
        if (chosenIndex == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el manager que será asignado", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Manager manager = managers.get(chosenIndex);
        if (manager == null) {
            JOptionPane.showMessageDialog(this, "No se ha podido determinar el manager seleccionado", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            CallableStatement stm = festival.getConnection().prepareCall("{call AsignarGrupoManager(?, ?)}");
            stm.setString(1, grupo.getId());
            stm.setString(2, manager.getId());

            stm.execute();

            festival.getConnection().commit();
            
            JOptionPane.showMessageDialog(this, "Se ha asignado el manager", "Manager asignado", JOptionPane.INFORMATION_MESSAGE);
            java.awt.EventQueue.invokeLater(() -> {
                this.setVisible(false);
            });
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, ex.toString(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAsignarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            this.setVisible(false);
        });
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAsignar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListManagers;
    private javax.swing.JLabel labelGrupo;
    private javax.swing.JScrollPane scrollManagers;
    // End of variables declaration//GEN-END:variables
}
